language: php

php:
  - 5.6
  - 7.0

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit tests --coverage-clover clover.xml --whitelist src

after_script: bash <(curl -s https://codecov.io/bash)
